### ISSUE TITLE
Add setting for color personalization

### ISSUE THREAD

**Issue by nrgapple** [supermedium/moonrider#46]
Add a section for setting the colors of the arrows for colored blind. And customization.

**Comment by dmarcos** [comment]
Got a couple of reports from reddit of people having trouble differentiating the colors. Wonder what’s the easiest solution? Would desaturating the block colors work? It would be nice if someone with issues gives us a couple of safe colors to play with.

**Comment by chrisplatorres** [comment]
Found this article on [How to Design for Color Blindness](https://usabilla.com/blog/how-to-design-for-color-blindness/)

> Since color blindness affects people in different ways, it’s difficult to determine which colors are ‘safe’ to use in web design

Blue & Purple made it onto their "here’s a few color combinations to avoid because they’re a potential nightmare to color blind users". 😐 

Perhaps a way that is mentioned is: adding texture to differentiate block colors.

**Comment by dmarcos** [comment]
In addition to color we could have an additional visual cue for right / left. We could have L / R text on the block or the ground or slightly different shapes.

**Comment by ngokevin** [comment]
Started the work on this: https://github.com/supermedium/moonrider/tree/colors

**Comment by ngokevin** [comment]
Added themes!
