### ISSUE TITLE
Haptic Feedback issue

### ISSUE THREAD

**Issue by Isafdor** [supermedium/moonrider#92]
Haptic feedback stops working after 1 minute of playing the game in any game mode. The controllers just don't vibrate anymore and I have to re-load the game for it to work only to stop working again after 1 minute. I'm using the Valve Index with Valve Index controllers with SteamVR open for clarification on my setup.

**Comment by Oliv6176** [comment]
I have the same problem with my oculus quest... Maybe it’s a webVR problem 🤔

**Comment by ngokevin** [comment]
yeah i think oculus browser maybe removed some haptics

**Comment by l3d00m** [comment]
I have an Oculus Quest and it works perfectly. I think I know what the issue is. Is it possible that not only the controllers do not vibrate anymore, but also you don't get any score? I.e. you can't hit the boxes anymore? @Oliv6176 

I had this happen quite regularly and I figured it happens when I move forward or backward in the room. I can move left and right without problems of course, but as soon as I move forward or backward the timing is totally off and I have to recenter. If that's isn't the cause for you, I'll open a new issue for my described problem. I think it would be fixed if moonrider would "recenter" automatically in the forward and backward direction or ignore that movement.

Besides that, thanks for the really cool game @ngokevin. I also have Beat Saber but I like this one more because it has cooler songs! Besides this issue it also worked really well for me. I'm astonished by how good WebVR works too.

**Comment by ngokevin** [comment]
@l3d00m thanks for the kind words and info. i think hit detection should be better now.

**Comment by l3d00m** [comment]
Hey @ngokevin, I just tested it out on my Oculus Quest with cleared oculus browser cache and unfortunately I don't have any haptic feedback anymore (previously that always worked for me). Song loading does work again now though :)

Also this does still happen for me:

> I can move left and right without problems of course, but as soon as I move forward or backward the timing is totally off and I have to recenter.

Thanks for all the new commits, appreciate the work!

**Comment by ngokevin** [comment]
I think Oculus Browser WebXR may have removed haptics unfortunately. @cabanier, is that right?

I'll check collision and timing. You mean the beats aren't on time, or hitting doesn't work?

**Comment by dmarcos** [comment]
Haptics unfortunately didn’t make it to the WebXR spec. The gamepad haptics extension was never standardized

**Comment by ngokevin** [comment]
Looks available in a way for now https://github.com/immersive-web/webxr-gamepads-module/issues/29

**Comment by dmarcos** [comment]
That was for Oculus Browser 8.5 maybe it was lost in 9.0?

**Comment by cabanier** [comment]
It was never hooked up to haptics module. Do you want me to try to hook it up?

**Comment by dmarcos** [comment]
Moonrider uses the [haptics component](https://github.com/supermedium/superframe/blob/master/components/haptics/index.js) that used to work with the old gamepad extension. Maybe some rewiring needed for WebXR.

**Comment by cabanier** [comment]
> Moonrider uses the [haptics component](https://github.com/supermedium/superframe/blob/master/components/haptics/index.js) that used to work with the old gamepad extension. Maybe some rewiring needed for WebXR.

Yes, [this code](https://github.com/supermedium/superframe/blob/master/components/haptics/index.js#L55) needs to be updated:

**Comment by dmarcos** [comment]
Thanks, I think fix shouldn't be much work.

**Comment by ngokevin** [comment]
Deployed haptics fix
